<script setup lang="ts">
import BaseLayout from "@/components/layouts/base-layout.vue";
</script>

<template>
  <base-layout full-width>
    <template #title>
      Whoops&thinsp;&mdash;&thinsp;that page has been abducted!
    </template>

    <template #subtitle>
      We couldn't find the page you were looking for. Please check the URL and try again.<br>
      In some cases, we may not want to disclose whether a page exists, so we'll show this page instead.
    </template>

    <figure>
      <img src="@/assets/404.png" alt="A picture of an alien abduction at night, seen from afar."/>
      <figcaption class="w-full max-w-6xl mx-auto px-4 text-xs text-gray-500 py-2">
        <span>
          Generated by <a href="https://openai.com/dall-e-3/" class="underline" rel="noopener nofollow" target="_blank">DALL·E 3</a>.
          Prompt: A valley at night, treeless mountains in the distance,  dark, bland, digital art, comic style.
        </span>
      </figcaption>
    </figure>
  </base-layout>
</template>
